version: '3.7'

services:
  mariadb:
    image: dipache/testlinkgrupo9project
    container_name: mariadb_testlink
    restart: always
    env_file:
      - params.txt
    networks:
      - testlink-network
    volumes:
      - mariadb_testlink_data:/dipache

  testlink:
    image: dipache/testlinkgrupo9project
    container_name: testlink
    restart: always
    ports:
      - ${PORT_HTTP:-80}:80
    env_file:
      - params.txt
    networks:
      - testlink-network
    volumes:
      - testlink_data:/bitnami
    depends_on:
      - mariadb
    environment:
      - TESTLINK_LANGUAGE=pt_BR
      - SMTP_ENABLE=${SMTP_ENABLE:-false}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_CONNECTION_MODE=${SMTP_CONNECTION_MODE}

volumes:
  mariadb_testlink_data:
    name: mariadb_testlink_data
  testlink_data:
    name: testlink_data

networks:
  testlink-network:
    name: testlink-network
    driver: bridge
