---
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/bitnami/mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink-archived:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '180:80'
      - '1443:443'
    volumes:
      - '/bitnami/testlink_data:/bitnami'
      - '/bitnami/php:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp
      - SMTP_PORT=25

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
